# error_handling1.py

# Use a try and except block, 
# to be able to execute the error_function.
# Can you have the except block print out the error that is raised 
# in the error_function?

### I AM NOT DONE

def error_function():
    raise ValueError("There was an error!") 

# edit code below

error_function()
